### ISSUE TITLE
Starting your Final Project

### ISSUE THREAD

**Issue by jonathan-rogers-dev** [jonathan-rogers-dev/Intro-To-Serverless#68]
Final Project Step 1 ⬤◯◯◯◯◯ | 🕐 Estimated completion: 1-2 hours

## ✅  Task:
- [ ] Create a new branch called `final-project`
    - Commit all of your final project related changes in the `final-project` branch
- [ ] Follow the template in "project/tech.md" file and plan out your project (directly edit the file)
    - Keep all of your final project related files in the "project" folder
- [ ] 🚀 Commit your changes to the `final-project` branch, make a pull request, and merge it

## Planning it out
1. In that tech.md, create a list of the Azure services you expect to create/use for your project and what specific purpose they serve for your project
2. Create a list of the external APIs you expect to create/use for your project and what specific purpose they serve for your project
3. Create a list of the npm packages, libraries, and/or databases you expect to create/use for your project and what specific purpose they serve for your project
4. Create a list of the frontend languages you expect to create/use for your project and what specific purpose they serve for your project

### Preparing a Checklist

As a beginner developer, it is vital that you consider the pros and cons of different technologies before you decide to use them. In this case, you are relatively profient with Azure functions and certain APIs, but for your final project you might find yourself looking into new softwares that you have't interacted before, talking to professionals about them, reading their documentation, and using them in your project.

<br>
<img src="https://i2.wp.com/allhtaccess.info/wp-content/uploads/2018/03/programming.gif?fit=1281%2C716&ssl=1" width=500>

> this you?

You will need to be able to justify your decisions confidently in order to prevent making decisions that will cost you excess time and effort in the developing phase. For this, you will need to start conducting extension research on how the technologies work and how they will be interacting with each other.

### Researching APIs (and other technologies)

<img src="https://developers.giphy.com/branch/master/static/api-c99e353f761d318322c853c03ebcf21b.gif" width=600>

There are thousands of amazing APIs that all have various functions, and there is no limit to the number of APIs you can use for your project.

#### How to find the right API?

1. Start with a simple Google search or filter through online lists such as [rapidapi.com](rapidapi.com) if you already know what purpose you want your API to serve (e.g. find a location, send an SMS, ...)
2. Research lists such as [rapidapi.com](https://rapidapi.com/categories) that have tags/categories that you can filter through to get some ideas if you're looking for 💡 project inspiration 💡 through cool new APIs
3.  Talk to people in the industry or try watching some API workshops to see what is out there

#### Popular API categories

- SMS notifications (e.g. Twilio API)
- Location based APIs
- Food related APIs
- Weather APIs

#### Examples of projects and which APIs they used

- [Dine the Distance](https://bitproject.org/blog/serverless-dine-the-distance) uses the Azure Maps API to get restaurant recommendations
- [Face Mask Detection](https://bitproject.org/blog/serverless-face-mask-detection) Tensorflow API for machine learning
- Flux uses the Power Grid API

<img src="https://twilio-cms-prod.s3.amazonaws.com/images/message-to-mail.width-808.gif" width=300>

Although these are great places to start, you might want to spice up your own project by using less conventional APIs as well that give your project an edge and make them stand out. This project is your crown jewel from the Serverless Camp. Make it memorable and have fun with it!

**Comment by jonathan-rogers-dev** [comment]
closed via oauth
