### ISSUE TITLE
Reviewing your Flowchart

### ISSUE THREAD

**Issue by jonathan-rogers-dev** [jonathan-rogers-dev/Intro-To-Serverless#71]
Final Project Step 3 ⬤⬤⬤◯◯◯ | 🕐 Estimated completion: 20-40 minutes

## ✅  Task:

- [x] Ask your mentor (or a friend) to carefully look over the flowchart and explain the project to you + take note if there are any holes in their explanation that you still need to visualize in the flowchart for it to make more sense
- [x] Explain the flowchart back to them and ask them if they have any feedback on how you can improve the use of technologies in your project
- [x] Use the feedback you improve your flowchart and update the file in the `final-project` branch
- [x] 🚀 Commit your changes to the `final-project` branch, make a pull request, and merge it
  - In the pull request description, explain the feedback you received and the changes you made

## How to improve a flowchart
There are 3 main things to focus on when you are getting feedback on and improving your flowchart:

#### :one: Logic:
  - Does the flowchart make sense?
  - Do the arrow directions makes sense?
  - Are the descriptions for the interactions between technologies logically correct?
#### :two: Accuracy: 
  - Did you include all components required for this project?
  - Do the arrows represent accurate relationships?
  - Are the descriptions accurate to what purposes the components serve?
#### :three: Readibility and visual appeal:
  - Is it easy to understand what is going on? Is there an easier way to explain it?
  - Are the colors/shapes simple and easy to read?
  - If you are using color codes, do you have a legend that describes what the colors mean?
  - Does the flowchart have a title?

<img src="https://github.com/natalieh235/songrecproject/raw/master/tutorial/images/flowchart.png" width=500/>
